# -*- coding: utf-8 -*-
"""damlayildiz_the4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiGKrHY086HuSmsCfdlp48r2y9xy3hl1
"""

# IMPLEMENT YOUR FUNCTIONS IN THIS CODE CELL OR
# IN THE PREVIOUS CODE CELL(S) THAT YOU MAY WANT TO CREATE

#Damla Yildiz

def import_inventory():
  dictionary = {}
  with open('products.txt', 'r') as file:
    lines = file.readlines()
    for line in lines:
      items = line.split('-')
      for item in items:
        name, count = item.split('_')
        name = name.lower().replace(' ', '')
        if name in dictionary.keys():
            dictionary[name] += int(count)
        else:
            dictionary[name] = int(count)
  return dictionary

def sell_product(products):
  sell_input = input('Please Enter Items: ')
  
  items = sell_input.split('-')
  for item in items:
    name, count = item.split('_')
    name = name.lower().replace(' ', '')
    if name in products.keys():
      if products[name] < int(count):
        print('There is not enough ', name, ' in inventory.')
      else:
        products[name] -= int(count)
        print(int(count), ' ', name, ' sold.')
        if products[name] == 0:
          products.pop(name)
    else:
        print(name, ' does not exist in inventory.')

def show_remaining(products):
  if len(products) == 0:
    print('Inventory is empty!')
  else:
    ct = 0
    products_array = []
    while len(products) != ct:
      products_array.append([list(products.keys())[ct], products[list(products.keys())[ct]]])
      ct += 1
    
    products_array.sort(key=lambda x: x[1])
    
    for item in products_array:
      print(item[0], ' : ', item[1])

# DO NOT MODIFY THIS CODE CELL, JUST RUN IT

products = import_inventory()
decision = ""
while decision != "3":
  print("*---------------------------")
  print("[1] Sell products")
  print("[2] Show remaining inventory")
  print("[3] Terminate")

  decision = input("Please enter your decision: ")
  print("____________________________")
  if decision == "1":
    sell_product(products)
  elif decision == "2":
    show_remaining(products)
  elif decision == "3":
    print("Terminating...")
  else:
    print("Invalid input!")